apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      # It is a good practice to declare resource requests and limits for both memory and cpu for each container. 
      # This helps to schedule the container to a node that has available resources for your Pod, and also so that 
      # your Pod does not use resources that other Pods needs - therefore the "this could starve other processes" message.
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"